<a href="https://colab.research.google.com/github/HaqqiLucky/Google-Collab/blob/master/preprocessingday1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Prerpocessing

In [6]:
import numpy as np
from sklearn import preprocessing

In [7]:
#define data

input_data = np.array([
    [5.1, -2.9, 3.3],
    [-1.2, 7.8, -6.1],
    [3.9, 0.4, 2.1],
    [7.3, -9.9, -4.5]
])

Binarization

thershold = di ambang, di ujung

In [8]:
data_binarized = preprocessing.Binarizer(threshold=2.2).transform(input_data)
print("\nBinarized data:\n", data_binarized)


Binarized data:
 [[1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


Mean Removal

In [9]:
print("\nBEFORE : ")
print("Mean = ", input_data.mean(axis=0))
print("Std Deviation = ", input_data.std(axis=0))


BEFORE : 
Mean =  [ 3.775 -1.15  -1.3  ]
Std Deviation =  [3.12039661 6.36651396 4.0620192 ]


In [10]:
#remove mean
data_scaled = preprocessing.scale(input_data)
print("\nAFTER : ")
print("Mean = ", data_scaled.mean(axis=0))
print("Std Deviation = ", data_scaled.std(axis=0))


AFTER : 
Mean =  [1.11022302e-16 0.00000000e+00 2.77555756e-17]
Std Deviation =  [1. 1. 1.]


Scaling

In [13]:
data_scaler_minmax = preprocessing.MinMaxScaler(feature_range=(0,1))
data_scaled_minmax = data_scaler_minmax.fit_transform(input_data)
print("\nMin max scaled data: \n", data_scaled_minmax)


Min max scaled data: 
 [[0.74117647 0.39548023 1.        ]
 [0.         1.         0.        ]
 [0.6        0.5819209  0.87234043]
 [1.         0.         0.17021277]]


Normalized

In [14]:
data_normalized_l1 = preprocessing.normalize(input_data, norm='l1')
data_normalied_l2 = preprocessing.normalize(input_data, norm='l2')
print(f"L1 : \n{data_normalized_l1}")
print(f"L2 : \n{data_normalied_l2}")


L1 : 
[[ 0.45132743 -0.25663717  0.2920354 ]
 [-0.0794702   0.51655629 -0.40397351]
 [ 0.609375    0.0625      0.328125  ]
 [ 0.33640553 -0.4562212  -0.20737327]]
L2 : 
[[ 0.75765788 -0.43082507  0.49024922]
 [-0.12030718  0.78199664 -0.61156148]
 [ 0.87690281  0.08993875  0.47217844]
 [ 0.55734935 -0.75585734 -0.34357152]]


Label Encoding

In [ ]:
import numpy as np
from sklearn import preprocessing

sampel data

In [15]:
input_label = ['merah', 'biru', 'hijau', 'ungu', 'putih', 'hitam']

In [16]:
# buat label encodernya

encoder = preprocessing.LabelEncoder()
encoder.fit(input_label)

LabelEncoder()

print mappingnya

In [19]:
print("\n Label Mapping: ")
for i, item in enumerate(encoder.classes_):
  print (item, '--->', i)

# ambil data random dari dataset
test_labels = ['merah', 'putih', 'ungu']
encoded_values = encoder.transform(test_labels)
print("\nLabel = ", test_labels)
print("Encoded values = ", list(encoded_values))

#ambil random angka
encoded_values = [5, 2, 1, 4]
decoded_list = encoder.inverse_transform(encoded_values)
print("\nEncoded values = ", encoded_values)
print("Decoded values = ", list(decoded_list))


 Label Mapping: 
biru ---> 0
hijau ---> 1
hitam ---> 2
merah ---> 3
putih ---> 4
ungu ---> 5

Label =  ['merah', 'putih', 'ungu']
Encoded values =  [3, 4, 5]

Encoded values =  [5, 2, 1, 4]
Decoded values =  ['ungu', 'hitam', 'hijau', 'putih']
